In [31]:
import pandas as pd
data = [
    ('Bijon', 38, 20000, 'Hyderabad', 'Kalyani', 9),
    ('Ankita', 34, 30000, 'Hyderabad', 'Baharampur', 4),
    ('Akriti', 5, 10, 'Hyderabad', 'Bangalore', 24)
]
df = pd.DataFrame(data=data, columns=['Name', 'Age', 'Salary', 'Residing Location', 'Place of Birth', 'Shoe size'])

In [32]:
df.head()

     Name  Age  Salary Residing Location Place of Birth  Shoe size
0   Bijon   38   20000         Hyderabad        Kalyani          9
1  Ankita   34   30000         Hyderabad     Baharampur          4
2  Akriti    5      10         Hyderabad      Bangalore         24

In [33]:
target_columns = ['Shoe size', 'Residing Location']
for column in target_columns:
    if column in df.columns:
        df.drop(column, axis=1, inplace=True)

df.head()

     Name  Age  Salary Place of Birth
0   Bijon   38   20000        Kalyani
1  Ankita   34   30000     Baharampur
2  Akriti    5      10      Bangalore

In [34]:
target_df = df['Place of Birth'].map({'Kalyani': 0, 'Baharampur': 1, 'Bangalore': 2})
target_df.head()

0    0
1    1
2    2
Name: Place of Birth, dtype: int64

In [35]:
df = pd.read_csv('/Users/bijonlahiri/Desktop/udemy_ml_network_security_project/Artifacts/18_02_26_12_25_22/data_validation/validated/train.csv')
df.columns

Index(['having_IP_Address', 'URL_Length', 'Shortining_Service',
       'having_At_Symbol', 'double_slash_redirecting', 'Prefix_Suffix',
       'having_Sub_Domain', 'SSLfinal_State', 'Domain_registeration_length',
       'Favicon', 'port', 'HTTPS_token', 'Request_URL', 'URL_of_Anchor',
       'Links_in_tags', 'SFH', 'Submitting_to_email', 'Abnormal_URL',
       'Redirect', 'on_mouseover', 'RightClick', 'popUpWidnow', 'Iframe',
       'age_of_domain', 'DNSRecord', 'web_traffic', 'Page_Rank',
       'Google_Index', 'Links_pointing_to_page', 'Statistical_report',
       'Result'],
      dtype='object')

In [31]:
import numpy as np
model_report = {}
model_list = ['abc', 'def', 'pqr', 'xyz']
for model in model_list:
    model_report[model] = {
        'f1': np.round(np.random.rand(), 2),
        'pre': np.round(np.random.rand(), 2),
        'rec': np.round(np.random.rand(), 2)
    }
# [report for report in model_report.values()]
best_f1 = max([report['f1'] for report in model_report.values()])
model_name = [name for name, report in model_report.items() if report['f1']==best_f1][0]
print(best_f1)
print(model_name)

0.65
xyz